name: Delete Microservice

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    env:
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      DB_URL: ${{ secrets.DB_URL }}
      NAME: "microservice"  # Set this to your specific service name
      RESOURCE_GROUP: "sit722sandara1"  # Adjust as necessary
      AKS_NAME: "sit722sandara1"         # Adjust as necessary

    steps:
      - name: Azure login
        run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_NAME

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete Kubernetes Resources
        run: |
          echo "Deleting Kubernetes resources defined in ${NAME}.yaml"
          ./scripts/delete.sh
